### ISSUE TITLE
🚀 Long Term Roadmap (LTR)

### ISSUE THREAD

**Issue by thewillyhuman** [weso/hermes#4]
# 🚧 This is our roadmap 🚧
This issue tracks high-level plans for hermes. It gives entry points for release-level issues as well as broader goals that correspond to rough milestones over the next year. In practice, these goals are pretty hit-and-miss w.r.t. people actually doing the necessary work, but they are reported here as aspirations and for discussion.

## Release plans
- [ ] hermes 1.0 beta - expected October 2020
- [ ] hermes 1.0 release candidate -  expected November 2020
- [ ] hermes 1.0 stable release -  expected December 2020
- [ ] hermes 2.0 beta - expected March 2021
- [ ] hermes 2.0 release candidate - expected April 2021
- [ ] hermes 2.0 stable release - expected May 2021
  - [ ] hermes 2.5 LTS - expected June 2020

## Primary focus of each version
* **hermes 1.0:** Translation from ShExCSV to ShExC.
* **hermes 2.0:** Binding with other programming languages and API Rest.
	* **hermes 2.5 LTS:** First production ready release with long term support 🎉.
